language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install flake8
install:
  - pip install -r requirements.txt
script:
  - py.test --cov=bcjoy tests/
